### ISSUE TITLE
about movement-speed

### ISSUE THREAD

**Issue by pandarua** [mmopluginteam/mmoitems#180]
Hello, I found that item stats about movement-speed doesn't work
my mmoitems version is 5.5.3
my server version is 1.15.2
Please reply me, thank you

**Comment by jacobmepstein** [comment]
Please update to the latest dev builds for MMOItems and MMOLib. 

MMOItems 5.5.4 - https://www.mythicmobs.net/index.php?pages/dev-mmoitems/
MMOLib 1.2.6 - https://github.com/mmopluginteam/mmolib/releases/

**Comment by Joshinn-mc** [comment]
@pandarua This is a known issue on 1.15.2 servers since Minecraft changed how movement speed works in 1.16.1, the movement speed stat will not work properly on latest versions of the plugins unless you update to 1.16.1 for the time being, we have duplicate  tickets reporting this so I will be closing this one to avoid clutter.
